version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    environment:
      - JWT_SECRET=secret_goes_in_here
    volumes:
      - trading_server_creds:/app/storage

volumes:
  trading_server_creds:
